### ISSUE TITLE
Documented the use of `#[used]`

### ISSUE THREAD

**Issue by Qix-** [Jess4Tech/limine-protocol#2]
I'm not going to pretend I know why this makes a difference, but for my `static` Limine decls that were somewhat "far" away from `_start` (in a deeply nested `mod` hierarchy), none of my responses were being populated until I annotated them with `#[used]`. Might be worthwhile to mention this somewhere in the docs?

**Comment by Jess4Tech** [comment]
This is a good idea and something I forgot to mention. The issue essentially amounts to LLVM considering them unused, resulting in them being trimmed. This will be done soon, so thanks for the heads up!

**Comment by Qix-** [comment]
That's what I figured was happening :) Sure thing, thanks for the great library!

**Comment by Jess4Tech** [comment]
Fixed in 0.4.3
